#!/bin/sh

echo "/volume1/${tsr_output_share}/tvstreamrecord.db"> "${SYNOPKG_PKGDEST}/db.ini"
echo ${tsr_output_share}> "${SYNOPKG_PKGDEST}/share.ini"

sed -i 's/common/${tsr_output_share}/' ${SYNOPKG_PKGDEST}/config.py
sed -i 's/\"cfg_recordpath\"/\"cfg_recordpath\" disabled=\"true\"/' ${SYNOPKG_PKGDEST}/views/config.tpl
sed -i 's/\"button_pathchooser\"/\"button_pathchooser\" disabled=\"true\"/' ${SYNOPKG_PKGDEST}/views/config.tpl
sed -i 's/\"button_database\"/\"button_database\" disabled=\"true\"/' ${SYNOPKG_PKGDEST}/views/config.tpl
exit 0